export const FETCH_QUOTES_LOADING = "FETCH_QUOTES_LOADING";
export const FETCH_QUOTES_SUCCESS = "FETCH_QUOTES_SUCCESS";
export const FETCH_QUOTES_ERROR = "FETCH_QUOTES_ERROR";
export const CHANGE_CATEGORY_QOUTES = "CHANGE_CATEGORY_QOUTES";
